2024-10-05 18:47:41,007 [INFO] - __main__ - create_new_doc(204) - created_new_doc(table=chat): new_doc.id=1
2024-10-05 18:49:02,987 [INFO] - __main__ - create_new_doc(204) - created_new_doc(table=chat): new_doc.id=2
2024-10-09 15:56:00,856 [ERROR] - __main__ - get_chat_with_user(177) - attempt=1 error: Could not determine join condition between parent/child tables on relationship Holiday.report - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2024-10-09 15:56:00,858 [ERROR] - __main__ - get_chat_with_user(177) - attempt=2 error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Holiday(holidays)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Holiday.report - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2024-10-09 15:56:00,858 [ERROR] - __main__ - get_chat_with_user(177) - attempt=3 error: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[Holiday(holidays)]'. Original exception was: Could not determine join condition between parent/child tables on relationship Holiday.report - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression.
2024-10-11 13:40:52,393 [ERROR] - __main__ - get_intersecting_users(37) - Attempt=1: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.InvalidColumnReferenceError'>: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
[SQL: SELECT DISTINCT ON (users.telegram_id) users.id, users.telegram_id, users.first_name, users.last_name, users.username, users.language_code, users.created_at, users.phone_number, users.birthday, users.status, users.info 
FROM users JOIN user_chat ON users.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id IN (SELECT user_chat.chat_id 
FROM user_chat 
WHERE user_chat.user_telegram_id = $1::BIGINT) AND users.telegram_id != $2::BIGINT AND users.birthday IS NOT NULL ORDER BY EXTRACT(month FROM users.birthday), EXTRACT(day FROM users.birthday)]
[parameters: (620527199, 620527199)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-10-11 13:40:53,160 [ERROR] - __main__ - get_intersecting_users(37) - Attempt=2: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.InvalidColumnReferenceError'>: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
[SQL: SELECT DISTINCT ON (users.telegram_id) users.id, users.telegram_id, users.first_name, users.last_name, users.username, users.language_code, users.created_at, users.phone_number, users.birthday, users.status, users.info 
FROM users JOIN user_chat ON users.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id IN (SELECT user_chat.chat_id 
FROM user_chat 
WHERE user_chat.user_telegram_id = $1::BIGINT) AND users.telegram_id != $2::BIGINT AND users.birthday IS NOT NULL ORDER BY EXTRACT(month FROM users.birthday), EXTRACT(day FROM users.birthday)]
[parameters: (620527199, 620527199)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-10-11 13:40:53,891 [ERROR] - __main__ - get_intersecting_users(37) - Attempt=3: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.InvalidColumnReferenceError'>: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
[SQL: SELECT DISTINCT ON (users.telegram_id) users.id, users.telegram_id, users.first_name, users.last_name, users.username, users.language_code, users.created_at, users.phone_number, users.birthday, users.status, users.info 
FROM users JOIN user_chat ON users.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id IN (SELECT user_chat.chat_id 
FROM user_chat 
WHERE user_chat.user_telegram_id = $1::BIGINT) AND users.telegram_id != $2::BIGINT AND users.birthday IS NOT NULL ORDER BY EXTRACT(month FROM users.birthday), EXTRACT(day FROM users.birthday)]
[parameters: (620527199, 620527199)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-10-12 20:34:28,008 [ERROR] - __main__ - create_system_data(31) - Attempt=1: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $3: '09:30' ('str' object cannot be interpreted as an integer)
[SQL: INSERT INTO system_data (title, data_digital, data_text, data_status) VALUES ($1::VARCHAR, $2::BIGINT, $3::INTEGER, $4::BOOLEAN) RETURNING system_data.id]
[parameters: ('check_birthday', 7, '09:30', None)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-12 20:34:28,226 [ERROR] - __main__ - create_system_data(31) - Attempt=2: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $3: '09:30' ('str' object cannot be interpreted as an integer)
[SQL: INSERT INTO system_data (title, data_digital, data_text, data_status) VALUES ($1::VARCHAR, $2::BIGINT, $3::INTEGER, $4::BOOLEAN) RETURNING system_data.id]
[parameters: ('check_birthday', 7, '09:30', None)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-12 20:34:28,401 [ERROR] - __main__ - create_system_data(31) - Attempt=3: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $3: '09:30' ('str' object cannot be interpreted as an integer)
[SQL: INSERT INTO system_data (title, data_digital, data_text, data_status) VALUES ($1::VARCHAR, $2::BIGINT, $3::INTEGER, $4::BOOLEAN) RETURNING system_data.id]
[parameters: ('check_birthday', 7, '09:30', None)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-12 20:34:28,414 [ERROR] - __main__ - get_system_data(46) - Attempt 1: Task <Task pending name='Task-7' coro=<get_system_data() running at /home/sergii/Загальне/projects/avrora/birthday_reminder_bot/src/sql/func_system_db.py:42> cb=[_run_until_complete_cb() at /usr/lib/python3.12/asyncio/base_events.py:182]> got Future <Future pending cb=[Protocol._on_waiter_completed()]> attached to a different loop
2024-10-12 20:38:10,255 [ERROR] - __main__ - get_system_data(46) - Attempt 1: Task <Task pending name='Task-5' coro=<get_system_data() running at /home/sergii/Загальне/projects/avrora/birthday_reminder_bot/src/sql/func_system_db.py:42> cb=[_run_until_complete_cb() at /usr/lib/python3.12/asyncio/base_events.py:182]> got Future <Future pending cb=[Protocol._on_waiter_completed()]> attached to a different loop
2024-10-13 20:32:55,706 [ERROR] - src.sql.func_db - get_all_users_from_chat(322) - attempt=1: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: -1001302960043 (value out of int32 range)
[SQL: SELECT user_chat.id, user_chat.chat_id, user_chat.user_telegram_id, user_chat.status, user_chat.updated_at, users_1.id AS id_1, users_1.telegram_id, users_1.first_name, users_1.last_name, users_1.username, users_1.language_code, users_1.created_at, users_1.phone_number, users_1.birthday, users_1.status AS status_1, users_1.info 
FROM user_chat LEFT OUTER JOIN users AS users_1 ON users_1.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id = $1::INTEGER]
[parameters: (-1001302960043,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-13 20:32:56,395 [ERROR] - src.sql.func_db - get_all_users_from_chat(322) - attempt=2: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: -1001302960043 (value out of int32 range)
[SQL: SELECT user_chat.id, user_chat.chat_id, user_chat.user_telegram_id, user_chat.status, user_chat.updated_at, users_1.id AS id_1, users_1.telegram_id, users_1.first_name, users_1.last_name, users_1.username, users_1.language_code, users_1.created_at, users_1.phone_number, users_1.birthday, users_1.status AS status_1, users_1.info 
FROM user_chat LEFT OUTER JOIN users AS users_1 ON users_1.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id = $1::INTEGER]
[parameters: (-1001302960043,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-13 20:32:57,073 [ERROR] - src.sql.func_db - get_all_users_from_chat(322) - attempt=3: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: -1001302960043 (value out of int32 range)
[SQL: SELECT user_chat.id, user_chat.chat_id, user_chat.user_telegram_id, user_chat.status, user_chat.updated_at, users_1.id AS id_1, users_1.telegram_id, users_1.first_name, users_1.last_name, users_1.username, users_1.language_code, users_1.created_at, users_1.phone_number, users_1.birthday, users_1.status AS status_1, users_1.info 
FROM user_chat LEFT OUTER JOIN users AS users_1 ON users_1.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id = $1::INTEGER]
[parameters: (-1001302960043,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-13 20:32:57,745 [ERROR] - src.sql.func_db - get_all_users_from_chat(322) - attempt=1: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: -1002435642587 (value out of int32 range)
[SQL: SELECT user_chat.id, user_chat.chat_id, user_chat.user_telegram_id, user_chat.status, user_chat.updated_at, users_1.id AS id_1, users_1.telegram_id, users_1.first_name, users_1.last_name, users_1.username, users_1.language_code, users_1.created_at, users_1.phone_number, users_1.birthday, users_1.status AS status_1, users_1.info 
FROM user_chat LEFT OUTER JOIN users AS users_1 ON users_1.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id = $1::INTEGER]
[parameters: (-1002435642587,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-13 20:32:58,425 [ERROR] - src.sql.func_db - get_all_users_from_chat(322) - attempt=2: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: -1002435642587 (value out of int32 range)
[SQL: SELECT user_chat.id, user_chat.chat_id, user_chat.user_telegram_id, user_chat.status, user_chat.updated_at, users_1.id AS id_1, users_1.telegram_id, users_1.first_name, users_1.last_name, users_1.username, users_1.language_code, users_1.created_at, users_1.phone_number, users_1.birthday, users_1.status AS status_1, users_1.info 
FROM user_chat LEFT OUTER JOIN users AS users_1 ON users_1.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id = $1::INTEGER]
[parameters: (-1002435642587,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-13 20:32:59,099 [ERROR] - src.sql.func_db - get_all_users_from_chat(322) - attempt=3: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: -1002435642587 (value out of int32 range)
[SQL: SELECT user_chat.id, user_chat.chat_id, user_chat.user_telegram_id, user_chat.status, user_chat.updated_at, users_1.id AS id_1, users_1.telegram_id, users_1.first_name, users_1.last_name, users_1.username, users_1.language_code, users_1.created_at, users_1.phone_number, users_1.birthday, users_1.status AS status_1, users_1.info 
FROM user_chat LEFT OUTER JOIN users AS users_1 ON users_1.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id = $1::INTEGER]
[parameters: (-1002435642587,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-13 20:32:59,772 [ERROR] - src.sql.func_db - get_all_users_from_chat(322) - attempt=1: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: -4008950322 (value out of int32 range)
[SQL: SELECT user_chat.id, user_chat.chat_id, user_chat.user_telegram_id, user_chat.status, user_chat.updated_at, users_1.id AS id_1, users_1.telegram_id, users_1.first_name, users_1.last_name, users_1.username, users_1.language_code, users_1.created_at, users_1.phone_number, users_1.birthday, users_1.status AS status_1, users_1.info 
FROM user_chat LEFT OUTER JOIN users AS users_1 ON users_1.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id = $1::INTEGER]
[parameters: (-4008950322,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-13 20:33:00,450 [ERROR] - src.sql.func_db - get_all_users_from_chat(322) - attempt=2: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: -4008950322 (value out of int32 range)
[SQL: SELECT user_chat.id, user_chat.chat_id, user_chat.user_telegram_id, user_chat.status, user_chat.updated_at, users_1.id AS id_1, users_1.telegram_id, users_1.first_name, users_1.last_name, users_1.username, users_1.language_code, users_1.created_at, users_1.phone_number, users_1.birthday, users_1.status AS status_1, users_1.info 
FROM user_chat LEFT OUTER JOIN users AS users_1 ON users_1.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id = $1::INTEGER]
[parameters: (-4008950322,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-13 20:33:01,137 [ERROR] - src.sql.func_db - get_all_users_from_chat(322) - attempt=3: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: -4008950322 (value out of int32 range)
[SQL: SELECT user_chat.id, user_chat.chat_id, user_chat.user_telegram_id, user_chat.status, user_chat.updated_at, users_1.id AS id_1, users_1.telegram_id, users_1.first_name, users_1.last_name, users_1.username, users_1.language_code, users_1.created_at, users_1.phone_number, users_1.birthday, users_1.status AS status_1, users_1.info 
FROM user_chat LEFT OUTER JOIN users AS users_1 ON users_1.telegram_id = user_chat.user_telegram_id 
WHERE user_chat.chat_id = $1::INTEGER]
[parameters: (-4008950322,)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2024-10-13 21:08:39,937 [INFO] - src.sql.func_db - create_new_doc(411) - created_new_doc(table=holiday): new_doc.id=1
2024-10-13 21:08:41,443 [INFO] - src.sql.func_db - create_new_doc(411) - created_new_doc(table=holiday): new_doc.id=2
2024-10-13 21:08:42,804 [INFO] - src.sql.func_db - create_new_doc(411) - created_new_doc(table=holiday): new_doc.id=3
